import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
    title: {
        default: 'LinkPage',
        template: '%s | Next.js',
        absolute: '',
    },
    description: "Generated by create next app",
};

export default function TitleMetadataLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <div className="m-6">
                    <ul className="flex">
                        <li className="mr-6 bg-amber-100 text-black pl-4 pr-4 rounded-md ">
                            <Link href="/link/link1">Link-1</Link>
                        </li>
                        <li className="mr-6 bg-amber-100 text-black pl-4 pr-4 rounded-md ">
                            <Link href="/link/link2">Link-2</Link>
                        </li>
                    </ul>
                </div>
                {children}
            </body>
        </html>
    );
}


//Browser URL:
// http://localhost:3000/link