import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { RootProvider } from "@/components/UserContext";
import Header from "@/components/Header";
// import { ErrorWrapper } from "./GlobalError";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    /**Context Provider Start*/
    <RootProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-s`}
        >
          <div className="h-screen">
            <div className=" bg-amber-900 p-6 flex justify-center">
              <div>Main Header</div>
              <div className="ml-10">
                <Link className={`mr-3 pt-3 pb-3 pl-4 pr-4 rounded-md bg-blue-400  hover:bg-amber-500`} href='/'>HOME</Link>
              </div>
            </div>
            <Header />
            {children}
            {/*GlobarError CUstomizetion */}
            {/* <ErrorWrapper>
            {children}
          </ErrorWrapper> */}
            <div className="mt-10 bg-amber-900 p-6 flex justify-center ">Main Footer</div>
          </div>
        </body>
      </html>
    </RootProvider>
    /**Context Provider End*/
  );
}
