import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
    title: {
        default: 'LinkPage',
        template: '%s | Next.js',
        absolute: '',
    },
    description: "Generated by create next app",
};

export default function TitleMetadataLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const linkId = 1;
    return (
        <html lang="en">
            <body>
                <div>
                    <h1>This is Link-1 Page</h1>
                    <div className="m-6">
                        <ul className="flex">
                            <li className="mr-6 bg-amber-100 text-black pl-4 pr-4 rounded-md ">
                                <Link href={`/link/link1/${linkId}`}>Link-ID-{linkId}</Link>
                            </li>
                            <li className="mr-6 bg-amber-100 text-black pl-4 pr-4 rounded-md ">
                                <Link href="/link/link1/2">Link-ID-2</Link>
                            </li>
                            <li className="mr-6 bg-amber-100 text-black pl-4 pr-4 rounded-md ">
                                <Link href="/link/link1/3">Link-ID-3</Link>
                            </li>
                            <li className="mr-6 bg-amber-100 text-black pl-4 pr-4 rounded-md ">
                                <Link href="/link/link1/4" replace>Back Home</Link>
                            </li>
                        </ul>
                    </div>
                </div>
                {children}
            </body>
        </html>
    );
}


//Browser URL:
// http://localhost:3000/link/link1