import type { Metadata } from "next";

export const metadata: Metadata = {
    title: {
        default: 'mDefaultTitle',
        template: '%s | Next.js',
        absolute: '',
    },
    description: "Generated by create next app",
};

export default function TitleMetadataLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`ntialiased`}
            >
                {children}
            </body>
        </html>
    );
}


//Browser URL:
// http://localhost:3000/metadata-title